name: Scale
version: '3.0.0'
main: net.sylviameows.scale.Core
description: Scale Plugin
api-version: '1.21.5'
bootstrapper: net.sylviameows.scale.Bootstrap

dependencies:
  # KittiLib provides kotlin and useful api for development.
  bootstrap:
    KittiLib:
      load: BEFORE
      required: true
  server:
    KittiLib:
      load: BEFORE
      required: true
